### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by Tumulte** [carlcarl/powerline-zsh#6]
Hey !

I've bumped on a bug in a french debian in the folder  /home/user/Téléchargement.

you bet that the "é" isn't python2 friendly and I got an encoding error (and no powerline).

Here's my hack : 
116     cwd = os.getenv('PWD')
->117     cwd = cwd.decode('utf-8', 'ignore')
#encoding returns ascii since default system encoding for python is ascii and shouldn't be changed

Also just in case I did this :
->303     cwd = cwd.decode('utf-8', 'ignore')
304     return cwd

have a nice day,

Tumulte

**Comment by carlcarl** [comment]
Hi, 
Thanks for your comment.
Could you help send me a pull request.
I'll apply this if it is OK.

**Comment by carlcarl** [comment]
Hi,
I'll close the issue. If you still have problem, please reopen it and give some comments.
Thanks.
